# Site settings
title: playing with pointers
email: sanjoy@playingwithpointers.com
description: > # this means to ignore newlines until "baseurl:"
  Sanjoy Das, Software Engineer. Blog on compilers, computer science, math, programming, virtual machines.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://playingwithpointers.com" # the base hostname & protocol for your site
twitter_username: SCombinator
github_username:  sanjoy
highlighter: pygments

# Build settings
markdown: kramdown

# exclude the deploy script
exclude: [ deploy.sh ]

sass:
  style: compressed

gems:
  - octopress-minify-html
